{
 "title": "Linux System",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "linux_host", "label": "linux_host", "query": "<ENTER HOST>" }
  ]
 },
 "panels": [
  {
   "title": "Host List",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "host" }
     ],
     "queryText": "SELECT distinct (host) FROM cpu \nWHERE $__timeRange(time)",
     "table": "cpu",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "uptime" }
     ],
     "queryText": "SELECT  \n  selector_last(uptime, time)['time'] AS time,\n  selector_last(uptime, time)['value'] AS uptime\nFROM system \nWHERE host='${linux_host}' AND time BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'",
     "table": "system",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "uptime" }
     ],
     "queryText": "SELECT  \n  selector_last(load1, time)['time'] AS time,\n  selector_last(load1, time)['value'] AS load1\nFROM system \nWHERE host='${linux_host}'  AND $__timeRange(time)",
     "table": "system",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "uptime" }
     ],
     "queryText": "SELECT  \n  selector_last(total, time)['time'] AS time,\n  selector_last(total, time)['value'] / 1024 / 1024 / 1024 As total\nFROM mem \nWHERE host='${linux_host}' AND $__timeRange(time)",
     "table": "system",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "nCPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "uptime" }
     ],
     "queryText": "SELECT  \n  selector_last(n_cpus, time)['time'] AS time,\n  selector_last(n_cpus, time)['value'] AS n_cpus\nFROM system \nWHERE host='${linux_host}' AND $__timeRange(time)",
     "table": "system",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "uptime" }
     ],
     "queryText": "SELECT  \n  selector_last(total_threads, time)['time'] AS time,\n  selector_last(total_threads, time)['value'] AS total_threads\nFROM processes \nWHERE host='${linux_host}' AND $__timeRange(time)",
     "table": "system",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "SELECT\n  $__dateBin(time) ,\n  avg(used_percent) AS 'average used_percent'\nFROM mem\nWHERE host='${linux_host}' AND $__timeRange(time)\nGROUP BY time\n\n\n",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 3 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "\nSELECT\n  $__dateBin(time) ,\n  avg(used_percent) AS 'average used_percent'\nFROM disk\nWHERE host='${linux_host}' AND $__timeRange(time)\nGROUP BY time",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 3 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "\n\n\nSELECT\n  $__dateBin(time) ,\n  avg(usage_user) AS 'usage_user',\n  avg(usage_system) AS 'usage_system',\n  avg(usage_idle) AS 'usage_idle'\nFROM cpu\nWHERE cpu='cpu-total' AND  $__timeRange(time)\nGROUP BY time",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "\n\n\nSELECT\n  $__dateBin(time) ,\n  avg(load1) AS 'load1',\n  avg(load5) AS 'load5',\n  avg(load15) AS 'load15'\nFROM system\nWHERE host='${linux_host}'  AND  $__timeRange(time)\nGROUP BY time",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "SELECT time, (read_bytes_delta_v / delta_t_ns) * 1000000000 as read_bytes, (write_bytes_delta_v / delta_t_ns) * 1000000000 as write_bytes\nFROM\n(\nSELECT\n  (lag(read_bytes, 1) OVER (ORDER BY time))  - read_bytes  as read_bytes_delta_v,\n   (lag(write_bytes, 1) OVER (ORDER BY time))  - write_bytes  as write_bytes_delta_v,\n  (lag(cast(time as bigint), 1) OVER (ORDER BY time)) - cast (time as bigint) as delta_t_ns,\n  time\nFROM\ndiskio\nWHERE host='${linux_host}' AND $__timeRange(time)\n) as sq\n",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "\nSELECT time, (bytes_recv_delta_v / delta_t_ns) * 1000000000 as read_bytes, (bytes_sent_delta_v / delta_t_ns) * 1000000000 as bytes_sent\nFROM\n(\nSELECT\n  (lag(bytes_recv, 1) OVER (ORDER BY time))  - bytes_recv  as bytes_recv_delta_v,\n  (lag(bytes_sent, 1) OVER (ORDER BY time))  - bytes_sent  as bytes_sent_delta_v,\n  (lag(cast(time as bigint), 1) OVER (ORDER BY time)) - cast (time as bigint) as delta_t_ns,\n  time\nFROM\nnet\nWHERE host='${linux_host}' AND $__timeRange(time)\n) as sq",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "SELECT\n  $__dateBin(time),\n  avg(running) AS 'running',\n  avg(blocked) AS 'blocked',\n  avg(idle) AS 'idle',\n  avg(unknown) AS 'unknown'\nFROM processes\nWHERE host='${linux_host}' AND $__timeRange(time)\nGROUP BY time ",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "columns": [
      { "value": "used_percent" }
     ],
     "queryText": "SELECT\n  $__dateBin(time),\n  avg(total) AS 'total',\n  avg(used) AS 'used'\nFROM swap\nWHERE host='${linux_host}' AND $__timeRange(time)\nGROUP BY time ",
     "table": "mem",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  }
 ]
}