{
 "title": "Vision AI",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Average Confidence",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT avg(confidence)\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Frame Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT selector_last(\"detection_frame_number\", time)['value'] AS frame\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Last Label",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT selector_last(\"label\", time)['value'] AS label\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Total detections in frame",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT selector_last(\"total_num_obj\", time)['value'] AS total\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Average Confidence",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 2 },
   "targets": [
    {
     "queryText": "SELECT confidence, obj, time\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Bounding Box Height & Width",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT \"box_width\", \"box_height\", obj, time\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Detection Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT label, obj, time\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Detection Status",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT label, obj, time, confidence,\"detection_frame_number\", \"coor_left\", \"coor_top\"\nFROM \"BW_Inference_results\"\nWHERE\n$__timeFilter(time) \nAND\n(\"confidence\" IS NOT NULL)"
    }
   ]
  }
 ]
}