FROM python:3

RUN mkdir demo
WORKDIR /demo
COPY generator_simulator/requirements.txt .
COPY generator_simulator/src .

RUN pip install --no-cache-dir -r requirements.txt


CMD [ "python", "emergency_generator.py" ]